{{ if eq .chezmoi.os "linux" }}
[".asdf"]
  type = "archive"
  url = "https://github.com/asdf-vm/asdf/archive/refs/tags/v0.10.2.tar.gz"
  stripComponents = 1
[".local/share/fonts/cascadia-code-nf"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.1/CascadiaCode.zip"
[".local/share/fonts/cascadia-code-ms"]
  type = "archive"
  url = "https://github.com/microsoft/cascadia-code/releases/download/v2111.01/CascadiaCode-2111.01.zip"
{{ end }}
